name = "chinai-api"
compatibility_date = "2026-06-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "chinai-api"
database_id = "a481353d-8a02-4767-8ac1-9d1bccb810af"

# KV 命名空间 (后续添加)
# [[kv_namespaces]]
# binding = "KV"
# id = "your-kv-id"
